### ISSUE TITLE
File comparisons don't work over SMB protocol and across folders

### ISSUE THREAD

**Issue by snovotill** [cfgnunes/nautilus-scripts#22]
Please find attached my implementation of "Select Left" and "Compare" scripts which works across different folders and via Gnome's SMB pseudo paths. It would be great to have this working in your scripts. I had to rename the files to a .txt extension becuause GitHub is a Windows shop.
[Compare.txt](https://github.com/cfgnunes/nautilus-scripts/files/14964144/Compare.txt)
[SelectLeft.txt](https://github.com/cfgnunes/nautilus-scripts/files/14964145/SelectLeft.txt)

**Comment by cfgnunes** [comment]
Hi @snovotill. Thanks for your request.

I have fixed this in the last version. Could you test it again?
(Commit: https://github.com/cfgnunes/nautilus-scripts/commit/67fef95c9f283cfd408ea11dc0a08480745d5cce)

**Comment by snovotill** [comment]
Hmm, I still get pop-up "You must select files or directories!" when I try to compare two files or two folders which are on a remote SMB share, via **Scripts ‣ Directories and files ‣Compare with diff**. On the other hand, the two script which I attached upon opening this ticket do work. I'm on Debian Trixie with Gnome-Wayland, but currently not quite Gnome 46 just yet. I'll debug this when Gnome 46 arrives, since the current Nautilus Scripts "API" is weirdly buggy. Until then, be well and stay relentless!

**Comment by cfgnunes** [comment]
Hi @snovotill. Thanks for your feedback.

I have fixed this in the last version. Could you test it again?

Now, I've tested on Debian Trixie with Gnome-Wayland using samba server (local and remote).

**Comment by snovotill** [comment]
Okay maestro, It's working perfectly now! Thanks for sharing =)

On another topic, I've attached a script for deleting files out of a PDF in case you're interested.
[DeletePdfPages.sh.txt](https://github.com/cfgnunes/nautilus-scripts/files/14994716/DeletePdfPages.sh.txt)
[ExtractPdfPages.sh.txt](https://github.com/cfgnunes/nautilus-scripts/files/14994722/ExtractPdfPages.sh.txt)

**Comment by cfgnunes** [comment]
Thanks for sharing the scripts.
About the scripts "DeletePdfPages.sh.txt" and "ExtractPdfPages.sh.txt" I use my scripts:

- Document PDF -> PDF combine, split -> Split into single-page PDFs
and after:
- Document PDF -> PDF combine, split -> Combine multiple PDFs

**Comment by snovotill** [comment]
You sure do! And those are two scripts which I did not have to write myself, along with MANY others☺ so thanks!
...and if you implement the "select left" with "compare" (try the examples which I attached) then you will have achieved GOD-level on the topic of Nautilus (and other) Scripts.
